// <auto-generated />
using System;
using LoanApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanApplication.Migrations
{
    [DbContext(typeof(LoanManagementDbContext))]
    [Migration("20260207103645_anotherMigration")]
    partial class anotherMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoanApplication.Domain.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AuditId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Borrower", b =>
                {
                    b.Property<int>("BorrowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BorrowerId"));

                    b.Property<string>("AlternatePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultedLoansCount")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployerOrBusiness")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GuarantorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GuarantorPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("InternalCreditScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationalIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("OnTimePaymentPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalLoansCount")
                        .HasColumnType("integer");

                    b.HasKey("BorrowerId");

                    b.HasIndex("NationalIdNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Borrowers");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.BorrowerDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocumentId");

                    b.HasIndex("BorrowerId");

                    b.ToTable("BorrowerDocuments");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Communication", b =>
                {
                    b.Property<int>("CommunicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommunicationId"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("integer");

                    b.Property<string>("CommunicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsAutomated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<int?>("LoanId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SentByUserId")
                        .HasColumnType("integer");

                    b.HasKey("CommunicationId");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanId");

                    b.HasIndex("SentByUserId");

                    b.ToTable("Communications");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoanId"));

                    b.Property<DateTimeOffset>("ApplicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DailyPenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("DisbursementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DisbursementMethod")
                        .HasColumnType("integer");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FirstPaymentDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastPaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("OutstandingPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PenaltyPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Phase1InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Phase2InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RepaymentDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalInterestAccrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPenaltiesAccrued")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LoanNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestPortion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PenaltyPortion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalPortion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("LoanId");

                    b.HasIndex("PaymentNumber")
                        .IsUnique();

                    b.HasIndex("RecordedByUserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.RepaymentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfterPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InterestPhase")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("LoanId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("LoanId");

                    b.ToTable("RepaymentSchedules");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.SystemConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.UserActivityLog", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ActivityId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.AuditLog", b =>
                {
                    b.HasOne("LoanApplication.Domain.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.BorrowerDocument", b =>
                {
                    b.HasOne("LoanApplication.Domain.Models.Borrower", "Borrower")
                        .WithMany("Documents")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Borrower");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Communication", b =>
                {
                    b.HasOne("LoanApplication.Domain.Models.Borrower", "Borrower")
                        .WithMany("Communications")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanApplication.Domain.Models.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId");

                    b.HasOne("LoanApplication.Domain.Models.User", "SentBy")
                        .WithMany()
                        .HasForeignKey("SentByUserId");

                    b.Navigation("Borrower");

                    b.Navigation("Loan");

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Loan", b =>
                {
                    b.HasOne("LoanApplication.Domain.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("LoanApplication.Domain.Models.Borrower", "Borrower")
                        .WithMany("Loans")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanApplication.Domain.Models.User", "CreatedBy")
                        .WithMany("CreatedLoans")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Borrower");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Payment", b =>
                {
                    b.HasOne("LoanApplication.Domain.Models.Loan", "Loan")
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanApplication.Domain.Models.User", "RecordedBy")
                        .WithMany("RecordedPayments")
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("RecordedBy");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.RepaymentSchedule", b =>
                {
                    b.HasOne("LoanApplication.Domain.Models.Loan", "Loan")
                        .WithMany("RepaymentSchedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.UserActivityLog", b =>
                {
                    b.HasOne("LoanApplication.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Borrower", b =>
                {
                    b.Navigation("Communications");

                    b.Navigation("Documents");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.Loan", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("RepaymentSchedules");
                });

            modelBuilder.Entity("LoanApplication.Domain.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedLoans");

                    b.Navigation("RecordedPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
